### ISSUE TITLE
Duplication in the error's stack and message

### ISSUE THREAD

**Issue by rstacruz** [power-assert-js/power-assert#19]
In mocha, the power-assert messages are displayed on both the stack and the message... it's a bit redundant.

![pasted_image_4_26_15__2_27_pm](https://cloud.githubusercontent.com/assets/74385/7336155/7accdc34-ec20-11e4-8a87-190f86d7e5b1.png)

**Comment by rstacruz** [comment]
Using this configuration: https://gist.github.com/rstacruz/f2fb7214d907aad1c250

**Comment by twada** [comment]
@rstacruz Thank you for reporting!

> In mocha, the power-assert messages are displayed on both the stack and the message... it's a bit redundant.

I think so too. This problem should be fixed ASAP.

Duplication appears since mocha 2.2.3, maybe since [this commit](https://github.com/mochajs/mocha/commit/8307cb4373ecede12975c04daa97e41cf34221ad).

I'll isolate the problem to determine which is wrong (power-assert or mocha), then fix or PR it soon.

Thanks!

**Comment by twada** [comment]
Ah this problem is due to [this change (Shorten stack traces)](https://github.com/mochajs/mocha/issues/545). Filepath is shortened to relative to the deploy folder, on the other hand Assertion message created by power-assert stores absolute filepath in the message.

I'll try to store relative paths in power-assert message.

**Comment by rstacruz** [comment]
heh, considering that feature came from my work, i guess indirectly I caused that ;)

**Comment by twada** [comment]
This issue is fixed by the [1.0.0 release](https://github.com/power-assert-js/power-assert/releases/tag/v1.0.0).
Feel free to reopen this if it is not fixed.

**Comment by rstacruz** [comment]
congrats on the 1.0 release!

**Comment by twada** [comment]
@rstacruz Thanks! :)
