### ISSUE TITLE
Does this work with substack/tape?

### ISSUE THREAD

**Issue by dbkaplun** [power-assert-js/power-assert#30]

**Comment by twada** [comment]
Short Answer: No.

Not yet. Once [we've tried to](https://github.com/azu/tape-power-assert/issues/1) and suspened for a while.

**Comment by twada** [comment]
[added to FAQ](https://github.com/power-assert-js/power-assert/commit/1e6e4c8280ef146a818a60aae0389428d260a4a5) then closed.
Thank you for your question.

**Comment by ELLIOTTCABLE** [comment]
Can you expand on this a bit, please? The README says that you can simply ‘use assert instead’ (i.e. not run your code through the power-assert module); wouldn't that mean that TAP is implicitly supported?

*How*, precisely, is TAP output not possible with power-assert?

**Comment by isiahmeadows** [comment]
@ELLIOTTCABLE 

Tape actually wraps Node's assertions directly, to something along the lines of this:

```js
// Obviously, it's a lot more sophisticated than this, because
// assertion messages need printed, etc.
var assert = require("assert")
Object.keys(assert).forEach(function (key) {
  Test.prototype[key] = function () {
    try {
      assert[key].apply(assert, arguments)
    } catch (e) {
      this.fail(e.message)
      return
    }
    this.pass()
  }
})
```

Because it wraps Node's native methods, and it does *not* catch and report thrown errors, there's no way to support it without either the user using [tape-catch](https://www.npmjs.com/package/tape-catch) or power-assert reinventing much of that and/or Tape's test handling magic.

**Comment by caesarsol** [comment]
Hi, is anything changed regarding to this? :)
