### ISSUE TITLE
[discussion] deepEqual on arrays 

### ISSUE THREAD

**Issue by iamstarkov** [power-assert-js/power-assert#41]
can we get fancy diff while `deepEqual`-ing two arrays?

right now, it's not neither fancy, neither helpful at all
```
  1. index › should esDepsResolved

  t.deepEqual(_, expected)
              |  |
              |  [#Object#,#Object#,#Object#,#Object#,#Object#,#Object#]
              [#Object#,#Object#,#Object#,#Object#,#Object#,#Object#]

      resolved: '/Users
        Decorator._callFunc (/Users/iamstarkov/projects/es-deps-resolved/node_modules/.store/empower-core@0.5.0/_/lib/decorator.js:110:20)
        Decorator.concreteAssert (/Users/iamstarkov/projects/es-deps-resolved/node_modules/.store/empower-core@0.5.0/_/lib/decorator.js:103:17)
        Object.decoratedAssert [as deepEqual] (/Users/iamstarkov/projects/es-deps-resolved/node_modules/.store/empower-core@0.5.0/_/lib/decorate.js:49:30)
        index.js:29:7
```

so, i have to do 

```js
  .then(_ => {
    t.deepEqual(_[0], expected[0]);
    t.deepEqual(_[1], expected[1]);
    t.deepEqual(_[2], expected[2]);
    t.deepEqual(_[3], expected[3]);
    t.deepEqual(_[4], expected[4]);
    t.deepEqual(_[5], expected[5]);
  }));
```

instead of just this

```js
  .then(_ => t.deepEqual(_, expected)));
```

**Comment by rymohr** [comment]
+1 and it's not just limited to arrays. All nested objects show up as `#Object#` and the diff gives you little to work from.

Is there a way to enable deeper diffs?

**Comment by twada** [comment]
Hi, thank you for using power-assert!

I assume you are using power-assert via AVA, and now AVA team is discussing about [changing default depth of power-assert rendering to 3](https://github.com/sindresorhus/ava/issues/681).

If you are using power-assert directly, please use configure output depth via [customization API](https://github.com/power-assert-js/power-assert#customization-api).

Thanks!

**Comment by iamstarkov** [comment]
thats cool, i'll close this issue, in favor of ava's one

**Comment by iamstarkov** [comment]
@twada that helped terms of detailed response
![screen shot 2016-04-08 at 14 02 07](https://cloud.githubusercontent.com/assets/559321/14383034/8db01260-fd92-11e5-8f58-8bc30746d325.png)

fancy diff might still be helpful, smth like [tap-diff](https://github.com/axross/tap-diff)
![screenshot1](https://cloud.githubusercontent.com/assets/559321/14383784/9167954a-fd97-11e5-9c55-46ef406bf5a4.png)

**Comment by iamstarkov** [comment]
@twada  can we get it somehow, or should we approach ava's optional tap output and use tap-diff directly?

**Comment by iamstarkov** [comment]
@twada what do you think about pretty diff?

**Comment by twada** [comment]
@iamstarkov I think providing pretty diff is a responsibility of testing framework (like Mocha or AVA), not matcher nor assertion library.
However power-assert should be responsible with prettying `BinaryExpression` (e.g.`foo === bar`) since testing framework doesn't have a way to detect expected and actual values.

Therefore, in my opinion, prettifying `deepEqual(foo, bar)` is still a responsibility of testing framework's various reporters. In contrast, prettifying `assert(foo === bar)` is a responsibility of power-assert.

But its a bit confusing.

There is two ways to solve this.

1. power-assert goes to framework agnostic, prettify `deepEqual`s as well
2. power-assert infer `expected` and `actual` of `BinaryExpression` then pass them to testing framework

I think plan `2` is simple, composable and promising for now.
