### ISSUE TITLE
Getter for customized options

### ISSUE THREAD

**Issue by watilde** [power-assert-js/power-assert#57]
Hi Lions!

In my karma plugin, I'm testing customized options only by comparing stdout with passed options, so it would be nice if I can access to the options I passed though `assert.customize`, to develop plugins in my case. It can be something like `assert.options` to return `extend(empowerOptions, options.assertion)` I guess.
+ https://github.com/watilde/karma-power-assert/blob/master/karma.conf.js#L9-L15
+ https://github.com/watilde/karma-power-assert/blob/master/test/adapter.spec.js#L14-L32

**Comment by twada** [comment]
Hi @watilde
Thank you for your suggestion!

However, I do not want to add more APIs to `assert`, not only that, I'm now thinking about deprecating `assert.customize` and deleting it from API at `power-assert 2.0.0`.

The reason is that I want `power-assert` to be completely compliant to Node's standard `assert` API and do not want users depend on power-assert original API. My hope is to make users start and stop using power-assert easily and transparently.

I'm not against adding `assert.options`, but against adding it as an API.
I can add `assert.options` as a SPI, for internal use and plugin authors only, and is not guaranteed its stability to end users.

What do you think?

**Comment by watilde** [comment]
Thanks for your courteous reply!
Basically I agreed 100% on the fact how `power-assert` should be, but let me just make sure. Eventually how can next version keep a way to customize `maxDepth`, or will drop the API and the feature as well completely in next major version?

**Comment by twada** [comment]
@watilde Thank you for your question.

> Eventually how can next version keep a way to customize maxDepth, or will drop the API and the feature as well completely in next major version?

In the future, options like `maxDepth` will be customized at compile time by configuration of instrumentors. Not at runtime.

That's why I'm going to deprecate `assert.customize` __as an API__, but not going to delete its implementation. `assert.customize` may remain as a SPI for a while. For tools like your product `karma-power-assert`.

**Comment by watilde** [comment]
Now it's so clear to me! Let me close this issue as resolved 😺
Looking forward to touch next version! Thanks.
