### ISSUE TITLE
Instant customization without side-effect

### ISSUE THREAD

**Issue by falsandtru** [power-assert-js/power-assert#64]
Could you support the following usage? It is helpful for instant debugging.

```
assert.customize({ output: { maxDepth: 2 } }).deepEqual([[0]], [[1]]);
```

**Comment by twada** [comment]
@falsandtru Thank you for your suggestion.

However, I do not want to support it now, not only that, I'm thinking about deprecating `assert.customize` and deleting it from power-assert API at power-assert 2.0.0.

The reason is that I want power-assert to be completely compliant to Node's standard assert API and do not want users depend on power-assert original API. My hope is to make users start and stop using power-assert easily and transparently.

In the future, options like `maxDepth` will be configured at transpile time by instrumentors. Not at runtime.

I'm sorry for the inconvenience. Please stay tuned.

**Comment by falsandtru** [comment]
I see, thanks!
